### ISSUE TITLE
Dataset path - temp

### ISSUE THREAD

**Issue by jbotteri** [modgeosys/fme-components#1]
Great development and very useful. Did notice one issue with Base64PNGRasterizer and the dataset specifed in PNGFeatureWriter.
![2022-06-13_14h47_04](https://user-images.githubusercontent.com/104610635/173297373-97333e02-dbfe-406e-87cd-0647093a3443.png)

**Comment by jbotteri** [comment]
Also this AttributeFileWriter will need the path updated
![image](https://user-images.githubusercontent.com/104610635/173301965-d520cbb5-1de3-4070-abb5-c936501191db.png)

**Comment by modgeosys** [comment]
Damn, I just now got notification on this.  Yes, FME has a nasty habit of replacing environment-neutral parameter values with hard-coded values whenever you make changes.  I'll address this one, and will also look into making the framework self-testing.

**Comment by modgeosys** [comment]
Fortunately, I completely reworked the Base64PNGRasterizer since this report (published July 11, 2022), and those transformers within are gone.  In fact, I don't write or read intermediate files for this process anymore.  But thank you for the report.  I've also updated my issue notification settings on github so I'll receive them more reliably.
